name       : tortoisehg
version    : 4.4.1
release    : 1
source     :
    - https://bitbucket.org/tortoisehg/targz/downloads/tortoisehg-4.4.1.tar.gz : 4355c39980fda3679292dc606d2e773c10a7aed80aa1a2afaac0970768493da8
license    : GPL-2.0
component  : programming.tools
summary    : TortoiseHg is a series of applications for the Mercurial distributed revision control system.
description: |
    TortoiseHg is a series of applications for the Mercurial distributed revision control system.
builddeps  :
    - pkgconfig(harfbuzz)
    - python-qscintilla
    - python-qt4
rundeps    :
    - mercurial
    - python-qscintilla
    - python-qt4
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm 00644 icons/scalable/apps/thg.svg $installdir/usr/share/icons/hicolor/scalable/apps/thg.svg
    sed -i "s|thg_logo|thg|" contrib/thg.desktop
    install -Dm 00644 contrib/thg.desktop $installdir/usr/share/applications/thg.desktop