name       : tortoisehg
version    : '4.7'
release    : 4
source     :
    - https://bitbucket.org/tortoisehg/targz/downloads/tortoisehg-4.7.tar.gz : 152fb92aa6787da73c0f75646432155921ae554b9d627b6b915eff887e6d29e9
license    : GPL-2.0-only
component  : programming.tools
summary    : TortoiseHg is a series of applications for the Mercurial distributed revision control system.
description: |
    TortoiseHg is a series of applications for the Mercurial distributed revision control system.
builddeps  :
    - pkgconfig(harfbuzz)
    - python-qscintilla
    - python-qt5
rundeps    :
    - mercurial
    - python-qscintilla
    - python-qt5
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 icons/scalable/apps/thg.svg $installdir/usr/share/icons/hicolor/scalable/apps/thg.svg
    sed -i "s|thg_logo|thg|" contrib/thg.desktop
    install -Dm00644 contrib/thg.desktop $installdir/usr/share/applications/thg.desktop
